# load(
#   "@build_bazel_rules_nodejs//:index.bzl",
#   "nodejs_binary",
# )
#
# nodejs_binary(
#   name = "generate_owners_json",
#   data = [":generateOwnersJson.js"],
#   entry_point = ":generateOwnersJson.js",
#   visibility = ["//:__subpackages__"],
# )
#
# nodejs_binary(
#   name = "combine_owners",
#   data = [":combineOwners.js"],
#   entry_point = ":combineOwners.js",
#   visibility = ["//:__subpackages__"],
# )
